### ISSUE TITLE
Breaks Pulse14

### ISSUE THREAD

**Issue by IamLunchbox** [tuxedocomputers/tuxedo.sh#29]
As mentioned in my E-Mail to the support, I will post this bug here for tracking purposes:

### Problem
On the Pulse 14 Laptop (running default Ubuntu 20.04) Tuxedo.sh adds the repos as expected. But after trying to build the amdgpu-tux dkms kernel, this port of the tuxedo.sh commands fail with error code 10. After a rollback the system is unable to reboot properly with the error: "Error decoding initramfs" and a following kernel panic.

Restarting Ubuntu and chosing recovery mode in GRUB and resuming the boot from there enables the functioning system. Rollback of the tuxedo.sh-changes via apt also failes, so the problems persists as soon as tuxedo.sh is evoked once. Changing the compression algorithm (a fix taken from a Linux Mint forum) didn't change the outcome of the reboot. 

### Additional Information
If it is unkown at tuxedo: Several amd specific drivers seem to be missing for the Pulse 14, using tuxedo.sh or the tuxedo package repositories didn't fix that issue. Furthermore, Tuxedo.sh doesn't fix the incorrectly assigned FN-Keys of the notebook, that issue was reported on other Pulse 14 as well, see /r/tuxedocomputers [https://www.reddit.com/r/tuxedocomputers/comments/ktaqa2/pulse_14_completely_wrong_fn_keys_with_tuxedo_os/](link).
Maybe a BIOS-Update would fix this issue, but then I would lose warrenty on my device?

**Comment by tuxedoxt** [comment]
Hello,

it sounds like the kernel installed in this case is not 5.6. Could you check which version is active after the configuration?

FYI AMD devices need at least kernel 5.5 (I believe, 5.6 in our current ubuntu based install) for basic support.

Regarding wrong keyboard layout. `tuxedo.sh` will not fix this. `tuxedo-keyboard` package also does not remap anything but provides drivers for some keys. Barring actually wrong printed layout, most likely outdated firmware is the case please contact the support for fix. Don't quote me but I believe you will not loose warranty if you do it yourself.

**Comment by IamLunchbox** [comment]
Thanks for the fast supply! I am actually using a vanilla ubuntu 20.04 after running apt update, upgrade, autoremove and autoclean:

```
uname -a
Linux hostname 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```
This is the exact OS, which broke under tuxedo.sh. I will fully backup my OS (in fear of Timeshift failing) and try to reproduce the issuse with logs.

Regarding the BIOS-Issue:
I double checked on tuxedocomputers.com again. The following statement comes from [this](https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/Updating-EFI-BIOS-EC.tuxedo) page:

> Important notice!
> 1. You assume full liability for a failed BIOS update. If problems should occur during or after the BIOS update, we can not repair your device within the scope of the warranty. If you want to perform a BIOS update, you need a USB stick on which you can copy the Shellx64.efi file as well as the EFI-BIOS or EC update suitable for your device.
> 2. Make sure to use the BIOS/EC files suitable for your notebook, otherwise you can irreparably damage your notebook.
> 3. If the downloaded folder contains a README.txt and/or LIESMICH.txt, follow the steps shown therein. If the downloaded folder does not contain either of these files, the steps shown in this manual apply.
> 4. Please make sure that the notebook is connected to the power supply, otherwise no BIOS/EC update/flash will be executed and it could be damaged. Unplug all USB devices from the notebook.
> 5. First the EC must be flashed and then the BIOS. On some models, mainly the XUX, there is a Main-EC & a 2nd-EC. First the Main-EC must be flashed and then the 2nd-EC must be flashed. This directly one behind the other!
> So only perform a BIOS/EC update if you are absolutely sure what you are doing!

The DOS-Bios update claims the following [here](https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/BIOS-update-using-DOS-shell.tuxedo):

> Important note
> You assume full liability for a failed BIOS update! If problems occur during or after the BIOS update, we CANNOT repair your device under warranty!
> If you want to perform a BIOS update, you will need a bootable DOS system for some older TUXEDO models. If your downloaded BIOS folder does not have a .nsh file, but instead mainly has .exe and .bat files, you will need to perform the flash operation using a DOS system.
> This guide should not be a problem for experienced users, however: only perform a BIOS update if you are absolutely sure what you are doing. Experience with handling CMD or terminals is more than just desired!

As far as I understand that, I would have to pay for a repair if the laptop breaks at a BIOS-Update or it gets bricked without any possiblity for repair. Both is not very appealing, but rather a matter to discuss with the support I guess.

**Comment by tuxedoxt** [comment]
Yeah regarding the firmware it should be available in the downloads section of your account. Other than that and the instructions from the page I'd have to refer you to the support. I'm sure they will have a solution, especially so as it does not even seem to have the correct layout.

Version 5.8 would also explain the issue with the `amdgpu-dkms`-package. I believe we have not yet upgraded from 5.6. The  `amdgpu-dkms` package is not supposed to be installed on kernels other than 5.6 so that would be a bug. Good news is that without it you could possibly be good to go as well.

I would recommend sorting out the firmware issue first to take the most advantage of the device and our services.

**Comment by IamLunchbox** [comment]
I have written the support on Sunday and will wait for a response from them. The drivers and firmware listed under my account are dated to the 23rd November, i'd expect that these are already included in the notebook I received 2 months later. Using them would again create problems with the warranty, but I'll contact tuxedo again.

Since I had to use my own Ubuntu-Install - Webfai was not working as intended (maybe the FW update again) - I automatically used kernel 5.8. After a short search there is no hint on the README's and Tuxedo-Website, that the current/newest kernel on Ubtuntu 20.04 LTS is **not** supported by tuxedo/tuxedo.sh. I would be grateful, if that would be mentioned somewhere, to same other people the hassle.

Edit:
I just rembered: When I executed tuxedo.sh it tried to compile the amdgpu-kernel for all 3 kernel versions currently installed (5.8, 5.6 and 5.4). If I now boot on kernel 5.6 and execute the script, it would probably still fail trying to compile a dkms kernel for the other two kernels, which are currently not used but rather function as fallback kernels (as Fedora and other distributions do as well). 
So maybe also update the documentation in that regard? I could issue a pull request, but I don't think I am sufficiently skilled in linux administration to use the correct terms and give advice on using the correct kernel.

**Comment by IamLunchbox** [comment]
Update:
I made a full system backup in case timeshift breaks again. I moved the system to Linux `5.6.1034-oem `, as needed by tuxedo.sh, and removed **all** other kernel versions. Additionally I used the supplied files to update EC and BIOS - it turns out no update was needed. A webfai-install still didn't work.

Executing tuxedo.sh now succeeds (after disabling timeshift-apt-autosnapshots) without dkms-errors. The only errors emerging are several cp-errors, there seem to be no checks before specific files are copied. The successful install...
- Broke initramfs again
- Left amd-navi drivers missing
- Disabled Redshift (when I boot via recovery)
- Didn't fix FN-Keys

**Comment by tuxedoxt** [comment]
I looked into the available firmware. The files for Pulse14 were even more outdated than I thought. Sorry for this inconvenience, I'll make sure they are updated and will let you know. This should fix Fn-keys and webfai.

**Comment by IamLunchbox** [comment]
Thank you for your help, it would be great to know which time frame for a fix can be expected and if a port on other distributions (e.g. fedora) is possible.

Will this fix the drivers issue as well?

**Comment by tuxedoxt** [comment]
The firmware should now be up to date, verified working with the installation and with the WebFAI (TUXEDO_OS/Ubuntu).

Please let me know how it works.

Edit: Which driver issue are you referring to?

**Comment by IamLunchbox** [comment]
I am referring to the amd-navi drivers, which apt claimed are missing. 

Regarding the firmware-update: It succeeded, the function-keys are correctly assigned and Webfai is successfully starting. I don't know if that will fix my issues with tuxedo.sh though, but I am uncertain if I will even try it. I'll close the bug report for now.

**Comment by tuxedoxt** [comment]
Yeah better hold off on using tuxedo.sh with this device for now until it can be overlooked.

Good that the WebFAI now is working. There should be no missing drivers or fixes after that install.

**Comment by fkaiserbio** [comment]
Dear @tuxedoxt,

I've purchased a Pulse 14 which finally got delivered. I've decided to install a vanilla Ubuntu 20.04.1 and still have the feeling that some functionality is not working and thus tried to install the drivers and TUXEDO packages with `tuxedo.sh` as you suggest on your website. Some of the things not working are, e.g.:

- right click with the touch pad is not set-up during a default Ubuntu installation
- touch pad lock with double click on upper left corner is not working

The wrong layout of Fn keys could be fixed by installing the latest EC and BIOS versions, as described above. However, when using `tuxedo.sh`, it breaks the boot of the notebook. In particular the following issues arise:

- amdgpu-dkms module cannot be build for any of the recent kernel versions and fails, e.g. with:
```
...
Loading new amdgpu-5.6.0.15-1098277-tux-1 DKMS files...
Building for 5.8.0-38-generic 5.8.0-40-generic
Building for architecture x86_64
Building initial module for 5.8.0-38-generic
cp: cannot stat '/usr/src/amdgpu-5.6.0.15-1098277-tux-1/firmware/amdgpu': No such file or directory
Error! Bad return status for module build on kernel: 5.8.0-38-generic (x86_64)
Consult /var/lib/dkms/amdgpu/5.6.0.15-1098277-tux-1/build/make.log for more information.
dpkg: error processing package amdgpu-dkms (--configure):
 installed amdgpu-dkms package post-installation script subprocess returned error exit status 10
...
```
- the added ACPI kernel parameters `acpi_osi= acpi_os_name=Linux acpi_backlight=vendor xhci_hcd.quirks=1073741824` added during `tuxedo.sh` call prevent boot and end up in a deadlock, a hard power cycle is required and boot works if these kernel parameters are removed

So I have the feeling that you should please reopen this issue until this is fixed.
 
Thanks for your help!

**Comment by IamLunchbox** [comment]
Hey,
  
if i recall correctly tuxedo.sh uses spefically kernel `5.6.0-1034-oem`and amdgpu-dmks will only compile with this kernel. You should see the cript installing the kernel before trying to compile.   
  

  
If the script encounters other kernels than 5.6.0-
  
1034, it will try to compile amdgpu-dkms for Thema too and fail, trying to rollback ALL kernel versions - breaking the system. So you'll need to remove every other kernel besides 5.6.1034-oem to successfully complete tuxedo.sh.   
  

  
But it might still crash your system with the correct kernel - it did that to me before the BIOS/EC-Update with the above mentioned initramfs error. My Webfai-install uses 5.6.0-1042 insteas btw...
  

    
  
  
>

**Comment by PhrozenByte** [comment]
`tuxedo.sh` is promoted to incorporate all changes necessary to install a vanilla Ubuntu and OpenSuse on a Tuxedo notebook. However, I don't think that this is actually true and never was true. See #10: The issue is two years old and wasn't really resolved yet. It rather feels like that Tuxedo OS and `tuxedo.sh` are more or less decoupled: Tuxedo works on Tuxedo OS and backports some (but not all, that's the problem) changes to `tuxedo.sh`. I don't feel like this is a good approach, issues are inevitable this way (like this one; a dev likely just forgot to backport some changes, no big deal, but evitable).

Priorities should be the other way round: `tuxedo.sh` should become the basis for Tuxedo OS. `tuxedo.sh` should include everything that distinguishes Tuxedo OS from a vanilla Ubuntu, differentiated by optional (like additional software or wallpapers) and required changes (like driver packages and firmware). A vanilla Ubuntu with `tuxedo.sh` and all options enabled should be identical to Tuxedo OS. I tried syncing `tuxedo.sh` and Tuxedo OS back in 2019 (see #9 and #11), but my changes never made it into `tuxedo.sh`. That's kinda frustrating, this was a lot of work!

My InfinityBook 14 v4 is now 2 years old and I'm thinking about buying a new device. However, right now I'm not so sure about whether Tuxedo is the best alternative. The hardware is amazing, but software not so much. I assume most Linux users want control over the software they use. `tuxedo.sh` is a great way to accomplish this, but it simply doesn't work. To be more precise, `tuxedo.sh` was one of the major reasons why I chose Tuxedo. So, @tuxedocomputers, what are your plans around `tuxedo.sh`?

**Comment by fkaiserbio** [comment]
> Hey, if i recall correctly tuxedo.sh uses spefically kernel `5.6.0-1034-oem`and amdgpu-dmks will only compile with this kernel. You should see the cript installing the kernel before trying to compile. If the script encounters other kernels than 5.6.0- 1034, it will try to compile amdgpu-dkms for Thema too and fail, trying to rollback ALL kernel versions - breaking the system. So you'll need to remove every other kernel besides 5.6.1034-oem to successfully complete tuxedo.sh. But it might still crash your system with the correct kernel - it did that to me before the BIOS/EC-Update with the above mentioned initramfs error. My Webfai-install uses 5.6.0-1042 insteas btw...
> […](#)

Thanks for your immediate feedback, I will try to compile with that kernel. However, it would be nice if `tuxedo.sh` would support the most recent Ubuntu kernels. The missing support of some features of the amazing hardware is really a pitty :frowning_face:  I would really much appreciate any work in this direction.

**Comment by tuxedoxt** [comment]
I'll attempt to address the questions... to some extent :)

@fkaiserbio Regarding `tuxedo.sh` and Pulse atm, yes there still seem to be issues there so, *this issue* still makes sense and since further recent kernel updates in Ubuntu it makes it tricky to maintain for this device regarding what `tuxedo.sh` normally does. This still needs to be looked over. So until then, for an as smooth experience as possible, please use the WebFAI.

To avoid confusion **our main way of installation and configuration is, and will for the foreseeable future remain, the WebFAI**.

> The missing support of some features of the amazing hardware is really a pitty

Which features are you missing?

I'll try to shortly clarify the kernel confusion and `amdgpu-dkms` addition for the curious. This is relevant for the newer AMD devices like Pulse and Polaris AMD version. Basic amdgpu support starts with 5.5 somewhere I believe. We're currently installing the 5.6-oem kernel. Although it has basic support some fixes regarding backlight are still missing. We patch these in a modified amdgpu-dkms package taken out of its context (and will only work for the current very specific kernels ;). From what I have seen though it just fails to build for the rest and does not cause further issues.

As we move on to newer kernels in the future these special arrangements will not be needed (at least for these devices) We take great care selecting what is installed and what is compatible with the devices.

As for fixes, like the kernel parameter set by Pulse, they are being moved to `tuxedo-tomte` which means much of what `tuxedo.sh` does/did is being replaced by `tuxedo-tomte`.

@PhrozenByte I am sorry that you are not happy with our Software. We do strive, as you say, to put the control in the hands of the users through ex TCC, configurability and to some extent the WebFAI. Hopefully more variation can be offered in the future.

BTW if you like the InfinityBook, the here discussed Pulse 14/15 are really nice and portable AMD alternatives ;) Otherwise there is the continued InfinityBook series with recently released IB S 14 gen 6 and IB S 15 gen 6.

**Comment by fkaiserbio** [comment]
@tuxedoxt Thanks for the response and detailed explanation :smiley: 

I will try to explain a bit more in detail what is happening with the hardware of Pulse 14. So, when on a vanilla Ubuntu 20.04 (without `tuxedo.sh`) with a recent kernel some base features are not working as expected. The physical right click button of the touch pad does not work out-of-the-box for example which is really annoying. Also the touch pad locking double tap is not working. Power delivery over USB C seems to be buggy as well and randomly switches on and off charging. I am also concerned regarding some power optimizations that might be not ideal. 

For me it would be very helpful if you could explain what `tuxedo.sh` does for Pulse 14 in detail. What is the meaning and purpose of the ACPI kernel parameters that break the boot?

Unfortunately, using the WebFAI is not an option for me unless you offer some customization options. For example, I am required to use a ZFS installation which, afaik, cannot be achieved with WebFAI.

**Comment by apoger** [comment]
WebFAI cannot be the default option for tuxedo customers. It's too limited (dual boot?). I bought a tuxedo for easy to use Linux compatible hardware. That one has to use a tuxedo.sh to get the basic functionality in an outdated Ubuntu is astonishing. That tuxedo.sh doesnt work flawlessly for newest Ubuntu and Debian is ridiculous. This, overall, hurts the Linux space. To get on topic: Your customers need to know what the tuxedo.sh does exactly. It's the bare minimum.

**Comment by PhrozenByte** [comment]
> Your customers need to know what the tuxedo.sh does exactly.

I don't think that this is the point @apoger. What `tuxedo.sh` does is kinda transparent, it's all in the script. Yeah, it's not very readable (#9 specifically addressed this, but never got merged), but in the end everything what `tuxedo.sh` does is in the script. The problem is that this is not enough to get a fully functional device.

IMO the problem is exactly what @tuxedoxt said (as problematized by @fkaiserbio):

> To avoid confusion our main way of installation and configuration is, and will for the foreseeable future remain, the WebFAI.

WebFAI is a black box. It's nearly impossible to comprehend what has changed in comparison to a vanilla Ubuntu (I tried with #10) and, more importantly, the changes differ from what `tuxedo.sh` does. Without any question, WebFAI is a good idea and is a huge improvement specifically for Linux starters, but personally I want control over my software. Besides the fact that WebFAI isn't very flexible. Thus WebFAI is no option for me. `tuxedo.sh` is an option, because it allows me to keep control. But `tuxedo.sh` simply doesn't work. So, what are my options? Loosing control over my software, or having a not fully functional device. The first is no option, and for the latter I can choose from a whole lot of other manufacturers. :disappointed:

**Comment by fkaiserbio** [comment]
So, I have digged a bit into `tuxedo.sh` and at least found a way to get a functional vanilla Ubuntu 20.04. Which features are lacking in comparison to a WebFAI installation - I can't tell. Here are the steps that I've taken:

- added TUEXDO debain sources to apt:
`$ echo "deb http://deb.tuxedocomputers.com/ubuntu focal main" >>  /etc/apt/sources.list` 
- get the key:
`$ wget -O - http://deb.tuxedocomputers.com/0x54840598.pub.asc | apt-key add -`
- update sources:
`$ apt-get update`
- install the binaries that `tuxedo.sh` does for Pulse 14:
`$ apt-get install tuxedo-keyboard tuxedo-control-center tuxedo-tomte`
- reboot

With this procedure I get rid of the issues I had. But seriously, this is not the way it should be :frowning_face: I would greatly appreciate if TUXEDO goes some steps towards their Linux enthusiast users and provides at least a transparent list of drivers required for each device and any further adaptions that might be required for a vanilla Linux.

**Comment by IamLunchbox** [comment]
You should still have driver issues with the amd-navi drivers, right? I consistently get apt notifications, that about 9 firmware-drivers with amd packages are missing...but I installed via WebFAI.

Regarding your workaround installing TCC via the deb-repositories of Tuxedo: Does redshift still work on your environment? I went down the same road and redshift stopped working (see my issue in tcc)

**Comment by tuxedoxt** [comment]
This issue turned a little bit too general and philosophical.

> It's too limited (dual boot?)

Simple dual boot options exist, please see
https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/I-want-to-work-with-Linux-and-Windows-Install-dual-boot.tuxedo

As for transparency, what fixes/adjustments do etc. sources are actually published here on github and some information is available on the web page, here for Pulse
https://www.tuxedocomputers.com/en/Infos/Help-Support/Help-for-my-device/TUXEDO-Pulse-series/TUXEDO-Pulse-14.tuxedo

I agree, there can always be more info, more up to date and in a clearer way. Especially for new devices this is one of the main problems. Keeping devices working through this time where support in the current kernel influenced by the distribution changes wildly.

> WebFAI is a black box. It's nearly impossible to comprehend what has changed in comparison to a vanilla Ubuntu

The good news is that the black box is getting smaller, more "vanilla" and adjustments are moved to packages that are more transparent like `tuxedo-tomte`.

Pulse is one of the tricky cases atm. Most devices will work fine with `tuxedo-tomte` + `tuxedo-keyboard` and recommended `tuxedo-control-center`. Pulse **for the moment** needs the specific oem kernel installed from the mirrors + `amdgpu-dkms` package from the mirrors. Depending on the current Ubuntu kernel this could mean that a "downgrade" is necessary.

**Comment by fkaiserbio** [comment]
> You should still have driver issues with the amd-navi drivers, right? I consistently get apt notifications, that about 9 firmware-drivers with amd packages are missing...but I installed via WebFAI.
> 
I'm not so sure about this. I'm running on a recent 5.8.0-40-generic at the moment and it seems that dedicated AMD drivers and kernel modules are not needed for that kernel any more. At least I cannot see any issues with my self-installed Ubuntu. All the drivers should come along with the kernel. The only thing that was added by `tuxedo-tomte` is the parameter `xhci_hcd.quirks=1073741824`.

> Regarding your workaround installing TCC via the deb-repositories of Tuxedo: Does redshift still work on your environment? I went down the same road and redshift stopped working (see my issue in tcc)
>
I'm not using redshift but Ubuntus native "Night Litght" function which does exactly the same. And this is running flawlessly, so I guess redshift would also.

Thanks @tuxedoxt  for pointing out the documentation page!
